version: '3.3'
services:
  influxdb:
    build: influxdb
    env_file: env.influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        networks:
      - internal_grafana
      --publish 8086:8086 \   #publishes port 80 in the container to port 8080 on the Docker hos
    
    
      
     
 
  grafana:
    build: grafana/grafana
    env_file: env.grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    links:
      - influxdb
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - internal_grafana
      --publish 3000:3000 \   #publishes port 80 in the container to port 8080 on the Docker hos
volumes:
  influxdb-storage:
  grafana-storage:
